Add JIT_EXPECT
ezyang/pytorch-unattached pull request #220
Opened 2017-09-12 18:18 UTC by houseroad

#120 

Introduce JIT_EXPECT. The implementation is almost the same as JIT_ASSERT.

Right now, if the check/assertion is directly on the user input, we call JIT_EXPECT.
Otherwise, we keep using JIT_ASSERT.

2017-09-12 19:06 UTC, ezyang commented
Good enough for now. I still want us to think about #144 but I am happy to take this patch now.

2017-09-12 19:25 UTC, apaszke requested changes
I think we shouldn't even have the `JIT_EXPECT` variant, because printing the expression that failed won't provide any value for the users. We should try to format the messages in a way that will tell them how can they fix their code (e.g. always provide the value you expected, and the one you got)

2017-09-12 19:25 UTC, apaszke commented on torch/csrc/jit/passes/onnx.cpp
> +        JIT_EXPECTM(node_it != op->inputs().end(), "expected too many inputs");
These two should be assertions

2017-09-12 19:25 UTC, apaszke commented on torch/csrc/jit/passes/onnx.cpp
> +      JIT_EXPECT(env.count(value) > 0);
This should remain an assertion

2017-09-12 19:25 UTC, apaszke commented on torch/csrc/autograd/functions/onnx/convolution.cpp
> +    JIT_EXPECT(p == 0);
Explicitly say that "output padding is not supported"

2017-09-13 02:56 UTC, apaszke commented on torch/csrc/jit/assert.h
> +                       #cond, ##__VA_ARGS__); \
`##__VA_ARGS__` is a GCC extension, so we shouldn't be using it. There's an easy hack to get around it:
```cpp
#define JIT_EXPECTM(...) _JIT_EXPECTM(__VA_ARGS__, ' ')

#define _JIT_EXPECTM(cond, msg, ...)
  if (__builtin_expect(!(cond), 0)) { \
    ::torch::jit::barf("%s:%u: %s: Invalid user input failed the check `%s`: " msg "%c", __FILE__, __LINE__, __func__, \
                       #cond, __VA_ARGS__); 
```

Also, I think the part "Invalid user input failed the check `%s`" is unnecessary. It doesn't add any value to the message, because users don't know the code, and when they get an error they look in their code first, so it's not necessary to mention that it's a user input check.

2017-09-13 05:52 UTC, houseroad commented on torch/csrc/jit/assert.h
> +                       #cond, ##__VA_ARGS__); \
Sounds good, will use the proposed alternative.

2017-09-13 19:07 UTC, merged